use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use crate::config::{BootConfig, EnvironmentConfig, ServiceConfig, SystemConfig, UserConfig};

const SYSTEM_CONFIG_FILE: &str = "system_config.toml";
const SERVICES_CONFIG_FILE: &str = "services.toml";
const USERS_CONFIG_FILE: &str = "users.toml";
const BOOT_CONFIG_FILE: &str = "boot_config.toml";

#[derive(Debug, Serialize, Deserialize)]
pub struct GenerationManifest {
    pub id: u64,
    pub packages: Vec<String>,
    pub created: SystemTime,
}

#[derive(Debug)]
pub struct Generation {
    pub id: u64,
    pub path: PathBuf,
    pub manifest: GenerationManifest,
}

pub struct GenerationStore {
    root: PathBuf,
}

impl GenerationStore {
    pub fn new(root: PathBuf) -> Result<Self> {
        fs::create_dir_all(&root)?;
        Ok(Self { root })
    }

    pub fn create<F>(
        &self,
        package_names: &[String],
        files: &[super::package::FileEntry],
        environment_config: EnvironmentConfig,
        system_config: Option<SystemConfig>,
        services_config: &HashMap<String, ServiceConfig>,
        users_config: &HashMap<String, UserConfig>,
        boot_config: Option<BootConfig>,
        linker: F,
    ) -> Result<u64>
    where
        F: Fn(&Option<String>, &Path) -> Result<()>,
    {
        let id = self.next_id()?;
        let gen_path = self.path(id);
        fs::create_dir_all(&gen_path)?;

        for file in files {
            let target = gen_path.join(file.path.trim_start_matches('/'));
            if let Some(target_path) = &file.symlink_target {
                if target.exists() || target.is_symlink() {
                    continue;
                }
                if let Some(parent) = target.parent() {
                    fs::create_dir_all(parent)?;
                }
                std::os::unix::fs::symlink(target_path, &target)?;
            } else {
                linker(&file.source_path, &target)?;

                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    fs::set_permissions(&target, fs::Permissions::from_mode(file.mode))?;
                }
            }
        }
        let session_variables = environment_config
            .session_variables
            .unwrap_or(HashMap::new())
            .into_iter()
            .map(|(k, v)| format!("{}={}", k, v))
            .collect::<Vec<String>>()
            .join("\n");
        fs::write(gen_path.join("session.env"), session_variables)?;
        let variables = environment_config
            .variables
            .unwrap_or(HashMap::new())
            .into_iter()
            .map(|(k, v)| format!("export {}={}", k, v))
            .collect::<Vec<String>>()
            .join("\n");
        fs::write(
            gen_path.join("variables.sh"),
            format!("# This file was generated by rscm.\n{}\n", variables),
        )?;

        if let Some(ref sys_config) = system_config {
            let sys_config_content = toml::to_string_pretty(sys_config)?;
            fs::write(gen_path.join(SYSTEM_CONFIG_FILE), sys_config_content)?;
        }

        if !services_config.is_empty() {
            let services_content = toml::to_string_pretty(services_config)?;
            fs::write(gen_path.join(SERVICES_CONFIG_FILE), services_content)?;
        }

        if !users_config.is_empty() {
            let users_content = toml::to_string_pretty(users_config)?;
            fs::write(gen_path.join(USERS_CONFIG_FILE), users_content)?;
        }

        if let Some(ref boot_cfg) = boot_config {
            let boot_content = toml::to_string_pretty(boot_cfg)?;
            fs::write(gen_path.join(BOOT_CONFIG_FILE), boot_content)?;
        }

        let manifest = GenerationManifest {
            id,
            packages: package_names.to_vec(),
            created: SystemTime::now(),
        };
        fs::write(
            gen_path.join("manifest.toml"),
            toml::to_string_pretty(&manifest)?,
        )?;
        Ok(id)
    }
    pub fn path(&self, id: u64) -> PathBuf {
        self.root.join(id.to_string())
    }

    pub fn delete(&self, id: u64) -> Result<()> {
        let gen_path = self.path(id);
        if gen_path.exists() {
            fs::remove_dir_all(gen_path)?;
        }
        Ok(())
    }
    pub fn list(&self) -> Result<Vec<Generation>> {
        let mut generations = Vec::new();
        for entry in fs::read_dir(&self.root)? {
            let entry = entry?;
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            if let Some(id_str) = path.file_name().and_then(|n| n.to_str()) {
                if let Ok(id) = id_str.parse::<u64>() {
                    let manifest_path = path.join("manifest.toml");
                    if manifest_path.exists() {
                        let content = fs::read_to_string(manifest_path)?;
                        let manifest = toml::from_str(&content)?;

                        generations.push(Generation { id, path, manifest });
                    }
                }
            }
        }
        generations.sort_by_key(|g| g.id);
        Ok(generations)
    }

    pub fn get(&self, id: u64) -> Result<Option<Generation>> {
        let path = self.path(id);
        let manifest_path = path.join("manifest.toml");
        if manifest_path.exists() {
            let content = fs::read_to_string(manifest_path)?;
            let manifest = toml::from_str(&content)?;
            Ok(Some(Generation { id, path, manifest }))
        } else {
            Ok(None)
        }
    }

    fn next_id(&self) -> Result<u64> {
        let mut max_id = 0;
        for entry in fs::read_dir(&self.root)? {
            let entry = entry?;
            if let Some(name) = entry.file_name().to_str() {
                if let Ok(id) = name.parse::<u64>() {
                    max_id = max_id.max(id);
                }
            }
        }
        Ok(max_id + 1)
    }
}
