pub mod content;
pub mod generation;
pub mod package;
pub mod reference;

pub use content::ContentStore;
pub use generation::{Generation, GenerationStore};
pub use package::{Package, PackageStore};
pub use reference::ReferenceCounter;

use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::Configuration;
use crate::store::generation::GenerationManifest;

pub struct Store {
    root: PathBuf,
    content: ContentStore,
    packages: PackageStore,
    generations: GenerationStore,
    reference: ReferenceCounter,
}

impl Store {
    pub fn new(root: PathBuf) -> Result<Self> {
        if !root.exists() {
            anyhow::bail!(
                "Store directory {} does not exist. Run 'rscm init' first to initialize storage.",
                root.display()
            );
        }
        let content = ContentStore::new(root.join("content"))?;
        let packages = PackageStore::new(root.join("packages"))?;
        let generations = GenerationStore::new(root.join("generations"))?;
        let reference = ReferenceCounter::new(root.join("references.json"))?;

        Ok(Self {
            root,
            content,
            packages,
            generations,
            reference,
        })
    }
    pub fn register_package(&mut self, pkg: Package) -> Result<()> {
        self.packages.save(&pkg)?;
        for file in &pkg.files {
            self.reference.add(&file.hash)?;
        }
        Ok(())
    }

    pub fn create_generation(&mut self, configuration: Configuration) -> Result<u64> {
        let mut files = Vec::new();
        // for name in configuration.packages.list {
        // if let Some(pkg) = self.packages.get(name)? {
        // for file in &pkg.files {
        // files.push(file.clone());
        // }
        // }
        // }
        self.generations
            .create(&[], &files, configuration.environment, |src, dst| {
                self.content.link_to(src, dst)
            })
    }

    pub fn activate_generation(&self, id: u64) -> Result<()> {
        let gen_path = self.generations.path(id);
        let current = Path::new("/rscm/current-system");
        if current.exists() {
            fs::remove_file(current.clone())?;
        }
        std::os::unix::fs::symlink(gen_path, current.clone())?;
        let manifest_path = current.join("manifest.toml");
        let manifest: GenerationManifest = toml::from_str(&fs::read_to_string(manifest_path)?)?;
        let env_file_path = current.join("session.env");
        let pam_env_path = Path::new("/etc/pam.d/rscm");
        fs::write(
            pam_env_path,
            format!(
                "# This file was generated by rscm\nsession  required  pam_env.so   readenv=1 envfile={}\n",
                env_file_path.display()
            ),
        )?;
        let env_path = Path::new("/etc/profile.d/rscm.sh");
        fs::write(
            env_path,
            format!(
                "# This file was generated by rscm.\n{}\n",
                manifest
                    .variables
                    .into_iter()
                    .map(|(k, v)| format!("export {}={}", k, v))
                    .collect::<Vec<String>>()
                    .join("\n")
            ),
        )?;
        Ok(())
    }
}
