pub mod content;
pub mod generation;
pub mod package;
pub mod reference;

pub use content::ContentStore;
pub use generation::{Generation, GenerationStore};
pub use package::{Package, PackageStore};
pub use reference::ReferenceCounter;

use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::Configuration;
use crate::lock::LockFile;
use crate::pkg::{BuildType, PackageConfig, PackageManagerFactory};
use crate::store::generation::GenerationManifest;

pub struct Store {
    root: PathBuf,
    content: ContentStore,
    packages: PackageStore,
    generations: GenerationStore,
    reference: ReferenceCounter,
    pkg_factory: PackageManagerFactory,
}

impl Store {
    pub fn new(root: PathBuf) -> Result<Self> {
        if !root.exists() {
            anyhow::bail!(
                "Store directory {} does not exist. Run 'rscm init' first to initialize storage.",
                root.display()
            );
        }
        let content = ContentStore::new(root.join("content"))?;
        let packages = PackageStore::new(root.join("packages"))?;
        let generations = GenerationStore::new(root.join("generations"))?;
        let reference = ReferenceCounter::new(root.join("references.json"))?;
        let pkg_factory = PackageManagerFactory::new(root.clone());

        Ok(Self {
            root,
            content,
            packages,
            generations,
            reference,
            pkg_factory,
        })
    }
    pub fn register_package(&mut self, pkg: Package) -> Result<()> {
        self.packages.save(&pkg)?;
        for file in &pkg.files {
            self.reference.add(&file.hash)?;
        }
        Ok(())
    }

    pub fn create_generation(
        &mut self,
        configuration: Configuration,
        lock: &LockFile,
    ) -> Result<u64> {
        let mut files = Vec::new();
        let mut package_names = Vec::new();

        for (name, pkg_versions) in &lock.packages {
            for (version_key, pkg_version) in &pkg_versions.versions {
                let full_name = format!("{}-{}", name, version_key);
                package_names.push(full_name.clone());

                if let Some(pkg) = self.packages.get(name)? {
                    for file in &pkg.files {
                        files.push(file.clone());
                    }
                } else {
                    println!("Installing package: {} ({})", name, version_key);
                    let is_aur = pkg_versions.source == "aur";
                    let build_type = if is_aur {
                        BuildType::Aur
                    } else {
                        BuildType::Pacman
                    };

                    let config = PackageConfig {
                        name: name.clone(),
                        version: Some(version_key.clone()),
                        build_type,
                        dependencies: pkg_version.dependencies.clone(),
                        sandbox_config: None,
                    };

                    let manager = self.pkg_factory.for_package(&config)?;
                    let info = manager.install(&config, false)?;

                    if let Some(pkg) = self.packages.get(name)? {
                        for file in &pkg.files {
                            files.push(file.clone());
                        }
                    }
                }
            }
        }

        self.generations.create(
            &package_names,
            &files,
            configuration.environment,
            |src, dst| self.content.link_to(src, dst),
        )
    }

    pub fn activate_generation(&self, id: u64) -> Result<()> {
        let gen_path = self.generations.path(id);
        let current = Path::new("/rscm/current-system");
        if current.exists() {
            fs::remove_file(current)?;
        }
        std::os::unix::fs::symlink(gen_path, current)?;
        let manifest_path = current.join("manifest.toml");
        let manifest: GenerationManifest = toml::from_str(&fs::read_to_string(manifest_path)?)?;
        let env_file_path = current.join("session.env");
        let pam_env_path = Path::new("/etc/pam.d/rscm");
        fs::write(
            pam_env_path,
            format!(
                "# This file was generated by rscm\nsession  required  pam_env.so   readenv=1 envfile={}\n",
                env_file_path.display()
            ),
        )?;
        let env_path = Path::new("/etc/profile.d/rscm.sh");
        std::os::unix::fs::symlink(current.join("variables.sh"), env_path)?;
        Ok(())
    }
    pub fn delete_generation(&self, id: u64) -> Result<()> {
        let current_link = Path::new("/rscm/current-system");
        if current_link.exists() {
            let current_target = fs::read_link(current_link)?;
            if let Some(current_name) = current_target.file_name().and_then(|n| n.to_str()) {
                if current_name == id.to_string() {
                    anyhow::bail!(
                        "Cannot delete generation {}: it is currently active. Use 'rscm switch' to switch to another generation first.",
                        id
                    );
                }
            }
        }
        self.generations.delete(id)
    }

    pub fn list_generations(&self) -> Result<Vec<Generation>> {
        self.generations.list()
    }
}
